---
title: "eds221-day3"
author: "Javier Patron"
date: "2022-08-10"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)


library(tidyverse)
```


### `If` Statements

```{r}
burrito <- 2.4

if (burrito > 2) {
  print("I love Burrito")
}
```

### String packages from the tiddyverse

```{r}
my_ships <- c("Millenium Falcon", "X-wing", "Tie-Fighter", "Death Star")
str_detect(my_ships, pattern = "X") #str_detect is case sensitive

phrase <- "i love burritos"
if (str_detect(phrase, "love")){
  print("Im a burrito fan")
}
```


### Example of the `%in%` operator
```{r}
tattoine_characters <- starwars |>
  filter(homeworld== "Tatooine")

# Use %in% operator to checl for multiple possitive matches
# Two options
#Option1
tatooine_endor_naboo <- starwars |> 
  filter(homeworld == "Tatooine" | homeworld == "Naboo" | homeworld == "Endor")
tatooine_endor_naboo

# Option 2
tatooine_naboo_endor <- starwars |> 
  filter(homeworld %in% c("Tatooine", "Endor", "Naboo"))

```


### Example of `if-else` statement

```{r}
pika = 50

if (pika > 60){
  print ("Mega pika")
} else {
  print ("Normal pika")
}
```


```{r}
marmot <- 2.8

if (marmot < 0.5){
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3){
  print("This is a medium marmot")
} else {
  print ("this is a large marmot")
}

```



